### ISSUE TITLE
The 4 trains simulations with Gibg injections will not run

### ISSUE THREAD

**Issue by asiaszmek** [neurord/ERK#1]
When I was trying to run the 4 trains with a Gibg injection simulations I ran into a specie (Gbuff) not present in the Reaction file error:
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar ~/new_neurord/neurord-3.2.3-all-deps.jar Model_ERK-stimd-GbgC100-cAMPC500-CaC1000-train4-inter1.xml 
18:49:51.113 W n.m.Reaction - no reactants in reaction cAMP
18:49:51.204 D n.u.NativeLib - Added /usr/lib64/jhdf to java.library.path (back)
18:49:51.204 D n.u.NativeLib - Added /usr/lib64/jhdf5 to java.library.path (back)
18:49:51.204 D n.u.NativeLib - Added /usr/lib/jhdf to java.library.path (back)
18:49:51.205 D n.u.NativeLib - Added /usr/lib/jhdf5 to java.library.path (back)
[main] INFO hdf.hdf5lib.H5 - HDF5 library: jhdf5
[main] INFO hdf.hdf5lib.H5 -  successfully loaded from java.library.path
18:49:51.262 E n.n.c.ReactionTable - Cannot find specie Gbuff
18:49:51.263 E n.n.BaseCalc - neurord.numeric.grid.AdaptiveGridCalc@f381794: failed (seed=123)
18:49:51.263 E n.SDCalc - Trial 0 failed!
 java.lang.RuntimeException: Cannot find specie Gbuff
	at neurord.numeric.chem.ReactionTable.getSpecieIndex(ReactionTable.java:329) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.numeric.chem.StimulationTable.<init>(StimulationTable.java:147) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.model.SDRun.getStimulationTable(SDRun.java:228) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.numeric.grid.AdaptiveGridCalc.init(AdaptiveGridCalc.java:49) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.numeric.grid.GridCalc._run(GridCalc.java:85) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.numeric.BaseCalc.run(BaseCalc.java:121) ~[neurord-3.2.3-all-deps.jar:?]
	at neurord.SDCalc.run(SDCalc.java:87) [neurord-3.2.3-all-deps.jar:?]
	at neurord.StochDiff.main(StochDiff.java:190) [neurord-3.2.3-all-deps.jar:?]

**Comment by prindia** [comment]
sorry just seeing this. was it fix?
